imports:
    - { resource: tables.yml }

services:
    marttiphpbb.communitycurrencies.main_listener:
        class: marttiphpbb\communitycurrencies\event\main_listener
        arguments:
            - @auth
            - @config
            - @controller.helper
            - %core.php_ext%
            - @template
            - @user
            - @marttiphpbb.communitycurrencies.datatransformer.currency_transformer
            - @marttiphpbb.communitycurrencies.model.links
        tags:
            - { name: event.listener }

    marttiphpbb.communitycurrencies.show_balance_listener:
        class: marttiphpbb\communitycurrencies\event\show_balance_listener
        arguments:
            - @auth
            - @config
            - @controller.helper
            - %core.php_ext%
            - @template
            - @user
            - @marttiphpbb.communitycurrencies.datatransformer.currency_transformer
        tags:
            - { name: event.listener }

    marttiphpbb.communitycurrencies.transaction.controller:
        class: marttiphpbb\communitycurrencies\controller\transaction
        arguments:
            - @auth
            - @cache
            - @config
            - @content.visibility
            - @dbal.conn
            - @pagination
            - %core.php_ext%
            - @request
            - @template
            - @user
            - @controller.helper
            - @marttiphpbb.communitycurrencies.datatransformer.currency_transformer
            - @marttiphpbb.communitycurrencies.transaction.operator
            - %core.root_path%
            - %tables.cc_transactions%
            - %tables.topics%
            - %tables.users%

    marttiphpbb.communitycurrencies.transaction.operator:
        class: marttiphpbb\communitycurrencies\operators\transaction
        arguments:
            - @cache
            - @config
            - @content.visibility
            - @dbal.conn
            - @user
            - @controller.helper
            - %tables.cc_transactions%
            - %tables.topics%
            - %tables.users%

    marttiphpbb.communitycurrencies.currency_plural.operator:
        class: marttiphpbb\communitycurrencies\operators\currency_plural
        arguments:
            - @cache
            - @config
            - @config_text
            - @dbal.conn
            - @user

    marttiphpbb.communitycurrencies.datatransformer.currency_transformer:
        class: marttiphpbb\communitycurrencies\datatransformer\currency_transformer
        arguments:
            - @config

    marttiphpbb.communitycurrencies.transaction.entity:
        class: marttiphpbb\communitycurrencies\entity\transaction
        arguments:
            - @dbal.conn
            - %tables.cc_transactions%

    marttiphpbb.communitycurrencies.notification.type.transaction:
        class: marttiphpbb\communitycurrencies\notification\transaction
        scope: prototype
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %core.root_path%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }

    marttiphpbb.communitycurrencies.model.links:
        class: marttiphpbb\communitycurrencies\model\links
        arguments:
            - @config
            - @template
            - @user
