imports:
    - { resource: tables.yml }

services:
    marttiphpbb.ccurrency.main_listener:
        class: marttiphpbb\ccurrency\event\main_listener
        arguments:
            - @auth
            - @config
            - @controller.helper
            - %core.php_ext%
            - @template
            - @user
            - @marttiphpbb.ccurrency.datatransformer.currency_transformer
        tags:
            - { name: event.listener }

    marttiphpbb.ccurrency.show_balance_listener:
        class: marttiphpbb\ccurrency\event\show_balance_listener
        arguments:
            - @auth
            - @config
            - @controller.helper
            - %core.php_ext%
            - @template
            - @user
            - @marttiphpbb.ccurrency.datatransformer.currency_transformer
        tags:
            - { name: event.listener }

    marttiphpbb.ccurrency.transaction.controller:
        class: marttiphpbb\ccurrency\controller\transaction
        arguments:
            - @auth
            - @cache
            - @config
            - @content.visibility
            - @dbal.conn
            - @pagination
            - %core.php_ext%
            - @request
            - @template
            - @user
            - @controller.helper
            - @marttiphpbb.ccurrency.datatransformer.currency_transformer
            - @marttiphpbb.ccurrency.transaction.operator
            - %core.root_path%
            - %tables.cc_transactions%
            - %tables.topics%
            - %tables.users%

    marttiphpbb.ccurrency.transaction.operator:
        class: marttiphpbb\ccurrency\operators\transaction
        arguments:
            - @cache
            - @config
            - @content.visibility
            - @dbal.conn
            - @user
            - @controller.helper
            - %tables.cc_transactions%
            - %tables.topics%
            - %tables.users%

    marttiphpbb.ccurrency.currency_plural.operator:
        class: marttiphpbb\ccurrency\operators\currency_plural
        arguments:
            - @cache
            - @config
            - @dbal.conn
            - @user
            - %tables.cc_currency_plural%

    marttiphpbb.ccurrency.datatransformer.currency_transformer:
        class: marttiphpbb\ccurrency\datatransformer\currency_transformer
        arguments:
            - @config

    marttiphpbb.ccurrency.transaction.entity:
        class: marttiphpbb\ccurrency\entity\transaction
        arguments:
            - @dbal.conn
            - %tables.cc_transactions%

    marttiphpbb.ccurrency.notification.type.transaction:
        class: marttiphpbb\calendar\notification\transaction
        scope: prototype
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %core.root_path%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }
